# Generated by Django 4.2.6 on 2023-11-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('blood', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'donortbl',
            },
        ),
    ]
